version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: ldp_database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_ldp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: ldp_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 82:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_ldp
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "83:80"
    restart: always
    networks:
      - dev
  www:
    build: .docker/php
    container_name: les_lames_du_ponant
    ports:
      - "84:80"
    volumes:
      - .docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    depends_on:
      - maildev
      - db
    networks:
      - dev

networks:
  dev: 

volumes:
  db-data:
