<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDTZghae\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDTZghae/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDTZghae.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDTZghae\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDTZghae\App_KernelDevDebugContainer([
    'container.build_hash' => 'DTZghae',
    'container.build_id' => '5b6aa928',
    'container.build_time' => 1595939198,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDTZghae');
