<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDtrNwxH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDtrNwxH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDtrNwxH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDtrNwxH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDtrNwxH\App_KernelDevDebugContainer([
    'container.build_hash' => 'DtrNwxH',
    'container.build_id' => '3ce06760',
    'container.build_time' => 1598455237,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDtrNwxH');
