<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnYNFVO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnYNFVO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMnYNFVO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMnYNFVO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMnYNFVO\App_KernelDevDebugContainer([
    'container.build_hash' => 'MnYNFVO',
    'container.build_id' => 'a4e7b26a',
    'container.build_time' => 1596484948,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnYNFVO');
